### ISSUE TITLE
Example password hashes in iPXE guide don't work

### ISSUE THREAD

**Issue by bwarden** [clearlinux/clear-linux-documentation#1251]
**Describe the error/improvement to an existing document or image**
The password hashes in the iPXE installation guide have extraneous backslashes inserted prior to `$` characters. As these fields are written as-is to `/etc/shadow` on the installed system, they are invalid password hashes, and will prevent login.
https://github.com/clearlinux/clear-linux-documentation/blob/cc16a5efd4cda85c7df849c3f03a51ebd557a835/source/get-started/ipxe-install.rst#L288
https://github.com/clearlinux/clear-linux-documentation/blob/cc16a5efd4cda85c7df849c3f03a51ebd557a835/source/get-started/ipxe-install.rst#L293

**Screenshots**
```
users:
- login: clrlinux
  username: Clear Linux
  # Password is "clear123"
  password: \$6\$SJJMfnInWQg.CvMA\$m2F8dJGj71zvi9mSNMktHMsPH3qhBm8pgXDNdaBe2yFfgi479JXvEqWkvQ6OxIUgGNQ5YXFIF0tCn.hEXB90G/
  admin: true
- login: root
  username: Root Root
  # Password is "clear123"
  password: \$6\$SJJMfnInWQg.CvMA\$m2F8dJGj71zvi9mSNMktHMsPH3qhBm8pgXDNdaBe2yFfgi479JXvEqWkvQ6OxIUgGNQ5YXFIF0tCn.hEXB90G/
  admin: true
```
